# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b398b4446e6eddca990432567f47f7276aafcfeea16413d3c3c141af9ee181918d84a9b37c746ce9bc7196c049976ecbd9e1181b5da8e30472ab9d1341a5fd05

test:
  secret_key_base: 1ca05c660b01329da32fc57734d01f279d124949ce1b702e0d3871169559664c6f3a7b0e4eee44f614b370def7876056a30cd85a7301f0f7af042b9da237d1e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  host: YOUR PRODUCTION HOST URL/IP HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>